name: CI for E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Configurar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # 3. Cache para dependencias de Gradle
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. Asignar permisos de ejecución al gradlew
      - name: Grant execute permissions for Gradle Wrapper
        run: chmod +x ./ejercicio1-E2E/gradlew

      # 5. Verificar Gradle Wrapper
      - name: Verify Gradle wrapper
        working-directory: ./ejercicio1-E2E
        run: ./gradlew wrapper --gradle-version 7.6.1

      # 6. Ejecutar las pruebas en modo headless
      - name: Run tests in headless mode
        working-directory: ./ejercicio1-E2E
        run: ./gradlew test --tests "com.nttdata.ejercicio1E2E.runner.EjecutarSerenity" --info
